version: '2'
services:
  easylearn-pack-service:
    build: .
    ports:
     - "8082:8080"
     - "8083:8081"
    links:
      - imagedb
    external_links:
      - easylearn-pack-service:packService
      - easylearn-user-service:userService
  imagedb:
    image: mongo
    ports:
     - "27018:27017"
